data_cfg:
  csv_path: metadata/rna_metadata.csv # CSV for path and metadata to training examples
  filtering:
    max_len: 150
    min_len: 40
  min_t: 0.01
  samples_per_eval_length: 5
  num_eval_lengths: 10
  batch_size: 28
  max_batch_size: 28
  max_squared_res: 19000
  max_num_res_squared: 19000
  eval_batch_size: 5
  num_workers: 4
  prefetch_factor: 100
  linear_effect: True

interpolant:
  min_t: 1e-2
  rots:
    train_schedule: linear
    sample_schedule: exp
    exp_rate: 10
  trans:
    train_schedule: linear
    sample_schedule: linear
  sampling:
    num_timesteps: 50
  self_condition: ${model.edge_features.self_condition}

model:
  use_flashipa: True
  mode: "flash_1d_bias" # 5 options: "orig_no_bias", "orig_2d_bias", "flash_no_bias", "flash_1d_bias", "flash_2d_factorize_bias"
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: False
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    embed_diffuse_mask: False
    max_num_res: 2000
    timestep_int: 1000
  edge_features:
    mode: ${model.mode}
    max_len: ${data_cfg.filtering.max_len}
    z_factor_rank: 2
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    use_rbf: True
    num_rbf: 32
    feat_dim: 64
    num_bins: 22
    self_condition: True
    k: 20
  ipa:
    use_flash_attn: True
    attn_dtype: bf16 # bf16, fp16, fp32. bf16 and fp16 for flash attn, fp32 for non-flash attn
    use_packed: True
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 128
    no_heads: 8
    z_factor_rank: ${model.edge_features.z_factor_rank}
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6

experiment:
  debug: False
  seed: 123
  num_devices: 1
  warm_start: null
  warm_start_cfg_override: True
  use_swa: False
  batch_ot:
    enabled: True
    cost: kabsch
    noise_per_sample: 1
    permute: False
  training:
    min_plddt_mask: null
    loss: se3_vf_loss
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_t_pass: 0.25
    tors_loss_scale: 1.0
    num_non_frame_atoms: 0 # choose from [0, 3, 7]
  wandb:
    name: rna-frameflow
    project: se3-fm
    save_code: false
    tags: []
    mode: "online" # can also save to `offline`
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    max_time: "00:20:00:00"
    min_epochs: 1
    max_epochs: 200
    accelerator: gpu
    log_every_n_steps: 10
    deterministic: False
    strategy: ddp_find_unused_parameters_true
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
  checkpointer:
    dirpath: ckpt/${experiment.wandb.project}/${experiment.wandb.name}/
    save_last: True
    save_top_k: 3
    monitor: train/loss
    mode: min
    every_n_epochs: 40
